version: '3.8'

services:
  php:
    image: studyforzx/hallucination-php:latest
    container_name: php
    volumes:
        - ./etc:/usr/local/etc/
        - ./log:/var/log/php/
        - /home/docker/nginx/html:/var/www/html
    restart: always
    network_mode: host
